- name: example for tags
  hosts: localhost
  connection: local
  tasks:
   - name: install nginx
     ansible.builtin.dnf:
      name: nginx
      state: present
     tags:
      - install
    
   - name: restart nginx
     ansible.builtin.systemd_service:
      name: nginx
      state: started
     tags:
      - restart
     